/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Client {
  'id' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'address' : string,
  'mobile' : string,
  'billingNumber' : string,
}
export interface Invoice {
  'id' : bigint,
  'clientId' : bigint,
  'createdAt' : bigint,
  'grandTotal' : number,
  'billingNumber' : string,
}
export interface Item {
  'id' : bigint,
  'rate' : number,
  'unit' : string,
  'description' : string,
  'quantity' : number,
  'roomId' : bigint,
  'amount' : number,
}
export interface Room {
  'id' : bigint,
  'name' : string,
  'invoiceId' : bigint,
  'subtotal' : number,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createClient' : ActorMethod<[string, string, string], bigint>,
  'createInvoice' : ActorMethod<[bigint], bigint>,
  'createItem' : ActorMethod<[bigint, string, number, string, number], bigint>,
  'createRoom' : ActorMethod<[bigint, string], bigint>,
  'deleteClient' : ActorMethod<[bigint], undefined>,
  'deleteInvoice' : ActorMethod<[bigint], undefined>,
  'deleteItem' : ActorMethod<[bigint], undefined>,
  'deleteRoom' : ActorMethod<[bigint], undefined>,
  'getAllClients' : ActorMethod<[], Array<Client>>,
  'getAllInvoices' : ActorMethod<[], Array<Invoice>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClient' : ActorMethod<[bigint], Client>,
  'getDashboardStats' : ActorMethod<
    [],
    {
      'totalBillingAmount' : number,
      'totalClients' : bigint,
      'totalInvoices' : bigint,
    }
  >,
  'getInvoice' : ActorMethod<[bigint], Invoice>,
  'getInvoicesByClientId' : ActorMethod<[bigint], Array<Invoice>>,
  'getItem' : ActorMethod<[bigint], Item>,
  'getItemsByRoomId' : ActorMethod<[bigint], Array<Item>>,
  'getRoom' : ActorMethod<[bigint], Room>,
  'getRoomsByInvoiceId' : ActorMethod<[bigint], Array<Room>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateClient' : ActorMethod<[bigint, string, string, string], undefined>,
  'updateInvoice' : ActorMethod<[bigint, bigint], undefined>,
  'updateItem' : ActorMethod<
    [bigint, string, number, string, number],
    undefined
  >,
  'updateRoom' : ActorMethod<[bigint, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];