/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Client = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'address' : IDL.Text,
  'mobile' : IDL.Text,
  'billingNumber' : IDL.Text,
});
export const Invoice = IDL.Record({
  'id' : IDL.Nat,
  'clientId' : IDL.Nat,
  'createdAt' : IDL.Int,
  'grandTotal' : IDL.Float64,
  'billingNumber' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Item = IDL.Record({
  'id' : IDL.Nat,
  'rate' : IDL.Float64,
  'unit' : IDL.Text,
  'description' : IDL.Text,
  'quantity' : IDL.Float64,
  'roomId' : IDL.Nat,
  'amount' : IDL.Float64,
});
export const Room = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'invoiceId' : IDL.Nat,
  'subtotal' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createClient' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'createInvoice' : IDL.Func([IDL.Nat], [IDL.Nat], []),
  'createItem' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Float64, IDL.Text, IDL.Float64],
      [IDL.Nat],
      [],
    ),
  'createRoom' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
  'deleteClient' : IDL.Func([IDL.Nat], [], []),
  'deleteInvoice' : IDL.Func([IDL.Nat], [], []),
  'deleteItem' : IDL.Func([IDL.Nat], [], []),
  'deleteRoom' : IDL.Func([IDL.Nat], [], []),
  'getAllClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
  'getAllInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClient' : IDL.Func([IDL.Nat], [Client], ['query']),
  'getDashboardStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalBillingAmount' : IDL.Float64,
          'totalClients' : IDL.Nat,
          'totalInvoices' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getInvoice' : IDL.Func([IDL.Nat], [Invoice], ['query']),
  'getInvoicesByClientId' : IDL.Func([IDL.Nat], [IDL.Vec(Invoice)], ['query']),
  'getItem' : IDL.Func([IDL.Nat], [Item], ['query']),
  'getItemsByRoomId' : IDL.Func([IDL.Nat], [IDL.Vec(Item)], ['query']),
  'getRoom' : IDL.Func([IDL.Nat], [Room], ['query']),
  'getRoomsByInvoiceId' : IDL.Func([IDL.Nat], [IDL.Vec(Room)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateClient' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateInvoice' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'updateItem' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Float64, IDL.Text, IDL.Float64],
      [],
      [],
    ),
  'updateRoom' : IDL.Func([IDL.Nat, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Client = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'address' : IDL.Text,
    'mobile' : IDL.Text,
    'billingNumber' : IDL.Text,
  });
  const Invoice = IDL.Record({
    'id' : IDL.Nat,
    'clientId' : IDL.Nat,
    'createdAt' : IDL.Int,
    'grandTotal' : IDL.Float64,
    'billingNumber' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Item = IDL.Record({
    'id' : IDL.Nat,
    'rate' : IDL.Float64,
    'unit' : IDL.Text,
    'description' : IDL.Text,
    'quantity' : IDL.Float64,
    'roomId' : IDL.Nat,
    'amount' : IDL.Float64,
  });
  const Room = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'invoiceId' : IDL.Nat,
    'subtotal' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createClient' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'createInvoice' : IDL.Func([IDL.Nat], [IDL.Nat], []),
    'createItem' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Float64, IDL.Text, IDL.Float64],
        [IDL.Nat],
        [],
      ),
    'createRoom' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
    'deleteClient' : IDL.Func([IDL.Nat], [], []),
    'deleteInvoice' : IDL.Func([IDL.Nat], [], []),
    'deleteItem' : IDL.Func([IDL.Nat], [], []),
    'deleteRoom' : IDL.Func([IDL.Nat], [], []),
    'getAllClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
    'getAllInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClient' : IDL.Func([IDL.Nat], [Client], ['query']),
    'getDashboardStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalBillingAmount' : IDL.Float64,
            'totalClients' : IDL.Nat,
            'totalInvoices' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getInvoice' : IDL.Func([IDL.Nat], [Invoice], ['query']),
    'getInvoicesByClientId' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Invoice)],
        ['query'],
      ),
    'getItem' : IDL.Func([IDL.Nat], [Item], ['query']),
    'getItemsByRoomId' : IDL.Func([IDL.Nat], [IDL.Vec(Item)], ['query']),
    'getRoom' : IDL.Func([IDL.Nat], [Room], ['query']),
    'getRoomsByInvoiceId' : IDL.Func([IDL.Nat], [IDL.Vec(Room)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateClient' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateInvoice' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'updateItem' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Float64, IDL.Text, IDL.Float64],
        [],
        [],
      ),
    'updateRoom' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };